language:
  - cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cmake libsqlite3-dev libboost-dev
env:
  - DB=sqlite://:memory: CMAKE_CXX_COMPILER=clang++
  - DB=sqlite://:memory: CMAKE_CXX_COMPILER=g++
  - DB=sqlite:///tmp/test.db CMAKE_CXX_COMPILER=g++
  - DB=sqlite:///tmp/test.db CMAKE_CXX_COMPILER=clang++
script:
  - mkdir build && cd build && cmake .. && make && make test