language:
  - cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cmake libsqlite3-dev libboost-dev
env:
  - DB=sqlite CMAKE_CXX_COMPILER=clang++
  - DB=sqlite CMAKE_CXX_COMPILER=g++
script:
  - mkdir build && cd build && cmake .. && make && make test