language:
  - cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cmake libsqlite3-dev libboost-dev valgrind
env:
  - DB="sqlite://:memory:"
  - DB="sqlite:///tmp/test.db"
script:
  - mkdir build 
  - cd build
  - cmake ..
  - make
  - make test
after_script:
  - valgrind --leak-check=full --show-reachable=yes --error-exitcode=1 ./tests/expressions/expressions
  - valgrind --leak-check=full --show-reachable=yes --error-exitcode=1 ./tests/query/query
  - valgrind --leak-check=full --show-reachable=yes --error-exitcode=1 ./tests/transaction/transaction
